//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 15/03/2019 11:55:31
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.ComponentModel;
using System.Reflection;
using System.Data.Common;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using BrainSystem.Pedidos.Model;

namespace BrainSystem.Pedidos.DAL
{

    public partial class BrainSystemDBContext : DbContext
    {

        public BrainSystemDBContext() :
            base()
        {
            OnCreated();
        }

        public BrainSystemDBContext(DbContextOptions<BrainSystemDBContext> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                optionsBuilder.UseSqlServer(@"Data Source=.\sql2008;Initial Catalog=TCMasterDB;Integrated Security=True;Persist Security Info=True");
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        public virtual DbSet<CLIENTESACCESOAPI> CLIENTESACCESOAPIs
        {
            get;
            set;
        }

        public virtual DbSet<SUBCLIEN> SUBCLIENs
        {
            get;
            set;
        }

        public virtual DbSet<TMDETPED> TMDETPEDs
        {
            get;
            set;
        }

        public virtual DbSet<MPOPEDC> MPOPEDCs
        {
            get;
            set;
        }

        public virtual DbSet<MPOPEDD> MPOPEDDs
        {
            get;
            set;
        }

        public virtual DbSet<TMCABPED> TMCABPEDs
        {
            get;
            set;
        }

        public virtual DbSet<RefreshToken> RefreshTokens
        {
            get;
            set;
        }
        public object CLIENTESACCESOAPI { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //IMPORTANT: FOR EACH TYPE returned by a raw query or stored procedure we must "register" here the query 
            //modelBuilder.Query<DBName>();
            this.CLIENTESACCESOAPIMapping(modelBuilder);
            this.CustomizeCLIENTESACCESOAPIMapping(modelBuilder);

            this.SUBCLIENMapping(modelBuilder);
            this.CustomizeSUBCLIENMapping(modelBuilder);

            this.TMDETPEDMapping(modelBuilder);
            this.CustomizeTMDETPEDMapping(modelBuilder);

            this.MPOPEDCMapping(modelBuilder);
            this.CustomizeMPOPEDCMapping(modelBuilder);

            this.MPOPEDDMapping(modelBuilder);
            this.CustomizeMPOPEDDMapping(modelBuilder);

            this.TMCABPEDMapping(modelBuilder);
            this.CustomizeTMCABPEDMapping(modelBuilder);

            this.RefreshTokenMapping(modelBuilder);
            this.CustomizeRefreshTokenMapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region CLIENTESACCESOAPI Mapping

        private void CLIENTESACCESOAPIMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CLIENTESACCESOAPI>().ToTable(@"CLIENTES_ACCESO_API", @"dbo");
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<string>(x => x.CODIGOCLIENTE).HasColumnName(@"CODIGO_CLIENTE").HasColumnType(@"char(10)").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<string>(x => x.USUARIOAPI).HasColumnName(@"USUARIO_API").HasColumnType(@"varchar(250)").IsRequired().ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<string>(x => x.PASSWORDAPI).HasColumnName(@"PASSWORD_API").HasColumnType(@"varchar(250)").IsRequired().ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<CLIENTESACCESOAPI>().HasKey(@"CODIGOCLIENTE", @"USUARIOAPI");
        }

        partial void CustomizeCLIENTESACCESOAPIMapping(ModelBuilder modelBuilder);

        #endregion


        #region SUBCLIEN Mapping

        private void SUBCLIENMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SUBCLIEN>().ToTable(@"SUBCLIEN", @"dbo");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.CLIENTE).HasColumnName(@"CLIENTE").HasColumnType(@"char(10)").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.CODIGO).HasColumnName(@"CODIGO").HasColumnType(@"char(10)").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.RAZONSOC).HasColumnName(@"RAZON_SOC").HasColumnType(@"char(60)").ValueGeneratedNever().HasMaxLength(60);
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.DOMICILIO).HasColumnName(@"DOMICILIO").HasColumnType(@"char(250)").ValueGeneratedNever().HasMaxLength(250).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.LOCALIDAD).HasColumnName(@"LOCALIDAD").HasColumnType(@"char(40)").ValueGeneratedNever().HasMaxLength(40).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.PROVINCIA).HasColumnName(@"PROVINCIA").HasColumnType(@"char(3)").ValueGeneratedNever().HasMaxLength(3).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.CP).HasColumnName(@"CP").HasColumnType(@"char(10)").ValueGeneratedNever().HasMaxLength(10).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.IVA).HasColumnName(@"IVA").HasColumnType(@"char(2)").ValueGeneratedNever().HasMaxLength(2).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.CUIT).HasColumnName(@"CUIT").HasColumnType(@"char(11)").ValueGeneratedNever().HasMaxLength(11).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.TARVIS).HasColumnName(@"TARVIS").HasColumnType(@"char(5)").ValueGeneratedNever().HasMaxLength(5).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.METVAL).HasColumnName(@"METVAL").HasColumnType(@"char(2)").ValueGeneratedNever().HasMaxLength(2).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.METFAC).HasColumnName(@"METFAC").HasColumnType(@"char(1)").ValueGeneratedNever().HasMaxLength(1).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.CONCOM).HasColumnName(@"CONCOM").HasColumnType(@"char(24)").ValueGeneratedNever().HasMaxLength(24).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.METAFO).HasColumnName(@"METAFO").HasColumnType(@"char(2)").ValueGeneratedNever().HasMaxLength(2).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.CODVAL).HasColumnName(@"CODVAL").HasColumnType(@"char(1)").ValueGeneratedNever().HasMaxLength(1).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.TARCAR).HasColumnName(@"TARCAR").HasColumnType(@"char(3)").ValueGeneratedNever().HasMaxLength(3).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.TELEFONO).HasColumnName(@"TELEFONO").HasColumnType(@"char(25)").ValueGeneratedNever().HasMaxLength(25).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.FAX).HasColumnName(@"FAX").HasColumnType(@"char(25)").ValueGeneratedNever().HasMaxLength(25).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.ZONA).HasColumnName(@"ZONA").HasColumnType(@"char(2)").ValueGeneratedNever().HasMaxLength(2).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.VENDEDOR).HasColumnName(@"VENDEDOR").HasColumnType(@"char(3)").ValueGeneratedNever().HasMaxLength(3).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.AREAMUELLE).HasColumnName(@"AREA_MUELLE").HasColumnType(@"char(6)").ValueGeneratedNever().HasMaxLength(6).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<decimal?>(x => x.DIASVTO).HasColumnName(@"DIASVTO").HasColumnType(@"decimal(3)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.PAIS).HasColumnName(@"PAIS").HasColumnType(@"char(3)").ValueGeneratedNever().HasMaxLength(3).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.RESERVA).HasColumnName(@"RESERVA").HasColumnType(@"char(9)").ValueGeneratedNever().HasMaxLength(9).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<decimal?>(x => x.PPICK).HasColumnName(@"PPICK").HasColumnType(@"decimal(12)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.HEDESDE).HasColumnName(@"HEDESDE").HasColumnType(@"char(10)").ValueGeneratedNever().HasMaxLength(10).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.HEHASTA).HasColumnName(@"HEHASTA").HasColumnType(@"char(10)").ValueGeneratedNever().HasMaxLength(10).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.NRORUC).HasColumnName(@"NRORUC").HasColumnType(@"char(12)").ValueGeneratedNever().HasMaxLength(12).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.FEDESDE).HasColumnName(@"FEDESDE").HasColumnType(@"char(6)").ValueGeneratedNever().HasMaxLength(6).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.FEHASTA).HasColumnName(@"FEHASTA").HasColumnType(@"char(6)").ValueGeneratedNever().HasMaxLength(6).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().Property<string>(x => x.CONTACTO).HasColumnName(@"CONTACTO").HasColumnType(@"char(200)").ValueGeneratedNever().HasMaxLength(200).HasDefaultValueSql(@"''");
            modelBuilder.Entity<SUBCLIEN>().HasKey(@"CLIENTE", @"CODIGO");
        }

        partial void CustomizeSUBCLIENMapping(ModelBuilder modelBuilder);

        #endregion


        #region TMDETPED Mapping

        private void TMDETPEDMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TMDETPED>().ToTable(@"TMDETPED", @"dbo");
            modelBuilder.Entity<TMDETPED>().Property<string>(x => x.EMPLAZA).HasColumnName(@"EMPLAZA").HasColumnType(@"char(3)").IsRequired().ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<TMDETPED>().Property<string>(x => x.ALMACEN).HasColumnName(@"ALMACEN").HasColumnType(@"char(3)").IsRequired().ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<TMDETPED>().Property<string>(x => x.TIPPEDIDO).HasColumnName(@"TIP_PEDIDO").HasColumnType(@"char(3)").IsRequired().ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<TMDETPED>().Property<string>(x => x.CATPEDIDO).HasColumnName(@"CAT_PEDIDO").HasColumnType(@"char(1)").ValueGeneratedNever().HasMaxLength(1);
            modelBuilder.Entity<TMDETPED>().Property<string>(x => x.SUCPEDIDO).HasColumnName(@"SUC_PEDIDO").HasColumnType(@"char(4)").ValueGeneratedNever().HasMaxLength(4);
            modelBuilder.Entity<TMDETPED>().Property<decimal?>(x => x.NROPEDIDO).HasColumnName(@"NRO_PEDIDO").HasColumnType(@"numeric(10)").ValueGeneratedNever();
            modelBuilder.Entity<TMDETPED>().Property<decimal>(x => x.LINEA).HasColumnName(@"LINEA").HasColumnType(@"numeric(10)").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<TMDETPED>().Property<string>(x => x.CIA).HasColumnName(@"CIA").HasColumnType(@"char(3)").IsRequired().ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<TMDETPED>().Property<string>(x => x.PRODUCTO).HasColumnName(@"PRODUCTO").HasColumnType(@"char(15)").IsRequired().ValueGeneratedNever().HasMaxLength(15);
            modelBuilder.Entity<TMDETPED>().Property<decimal?>(x => x.CANTIDAD).HasColumnName(@"CANTIDAD").HasColumnType(@"numeric(13,2)").ValueGeneratedNever();
            modelBuilder.Entity<TMDETPED>().Property<string>(x => x.LOTEUNICO).HasColumnName(@"LOTE_UNICO").HasColumnType(@"char(1)").IsRequired().ValueGeneratedNever().HasMaxLength(1);
            modelBuilder.Entity<TMDETPED>().Property<string>(x => x.DESPPARCI).HasColumnName(@"DESP_PARCI").HasColumnType(@"char(1)").IsRequired().ValueGeneratedNever().HasMaxLength(1);
            modelBuilder.Entity<TMDETPED>().Property<string>(x => x.LOTE).HasColumnName(@"LOTE").HasColumnType(@"char(15)").IsRequired().ValueGeneratedNever().HasMaxLength(15);
            modelBuilder.Entity<TMDETPED>().Property<string>(x => x.SERIE).HasColumnName(@"SERIE").HasColumnType(@"char(15)").ValueGeneratedNever().HasMaxLength(15);
            modelBuilder.Entity<TMDETPED>().Property<decimal>(x => x.ID).HasColumnName(@"ID").HasColumnType(@"numeric(18)").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<TMDETPED>().Property<string>(x => x.ESTPROD).HasColumnName(@"EST_PROD").HasColumnType(@"char(3)").ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<TMDETPED>().Property<decimal>(x => x.KILOS).HasColumnName(@"KILOS").HasColumnType(@"numeric(9,3)").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<TMDETPED>().HasKey(@"ID");
        }

        partial void CustomizeTMDETPEDMapping(ModelBuilder modelBuilder);

        #endregion

        #region MPOPEDC Mapping

        private void MPOPEDCMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MPOPEDC>().ToTable(@"MPOPEDC", @"dbo");
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.EMPLAZA).HasColumnName(@"EMPLAZA").HasColumnType(@"char(3)").IsRequired().ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.ALMACEN).HasColumnName(@"ALMACEN").HasColumnType(@"char(3)").IsRequired().ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.TIPPEDIDO).HasColumnName(@"TIP_PEDIDO").HasColumnType(@"char(3)").IsRequired().ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.CATPEDIDO).HasColumnName(@"CAT_PEDIDO").HasColumnType(@"char(1)").IsRequired().ValueGeneratedNever().HasMaxLength(1);
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.SUCPEDIDO).HasColumnName(@"SUC_PEDIDO").HasColumnType(@"char(4)").IsRequired().ValueGeneratedNever().HasMaxLength(4);
            modelBuilder.Entity<MPOPEDC>().Property<decimal>(x => x.NROPEDIDO).HasColumnName(@"NRO_PEDIDO").HasColumnType(@"numeric(10)").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<MPOPEDC>().Property<System.DateTime>(x => x.FECHA).HasColumnName(@"FECHA").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.CLIENTE).HasColumnName(@"CLIENTE").HasColumnType(@"char(10)").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.SUBCLIENTE).HasColumnName(@"SUBCLIENTE").HasColumnType(@"char(10)").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.RAZONSOC).HasColumnName(@"RAZON_SOC").HasColumnType(@"char(60)").ValueGeneratedNever().HasMaxLength(60);
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.DOMICILIO).HasColumnName(@"DOMICILIO").HasColumnType(@"char(250)").ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.LOCALIDAD).HasColumnName(@"LOCALIDAD").HasColumnType(@"char(40)").ValueGeneratedNever().HasMaxLength(40);
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.PROVINCIA).HasColumnName(@"PROVINCIA").HasColumnType(@"char(30)").IsRequired().ValueGeneratedNever().HasMaxLength(30);
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.CP).HasColumnName(@"CP").HasColumnType(@"char(10)").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<MPOPEDC>().Property<bool>(x => x.PARTICIONA).HasColumnName(@"PARTICIONA").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<MPOPEDC>().Property<System.DateTime>(x => x.FENTREGA).HasColumnName(@"F_ENTREGA").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.REFA).HasColumnName(@"REF_A").HasColumnType(@"char(30)").ValueGeneratedNever().HasMaxLength(30).HasDefaultValueSql(@"''");
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.REFB).HasColumnName(@"REF_B").HasColumnType(@"char(30)").ValueGeneratedNever().HasMaxLength(30).HasDefaultValueSql(@"''");
            modelBuilder.Entity<MPOPEDC>().Property<decimal>(x => x.VALFACTUR).HasColumnName(@"VAL_FACTUR").HasColumnType(@"numeric(13,2)").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<MPOPEDC>().Property<decimal>(x => x.VALCONTRA).HasColumnName(@"VAL_CONTRA").HasColumnType(@"numeric(13,2)").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.CENCOS).HasColumnName(@"CENCOS").HasColumnType(@"char(10)").ValueGeneratedNever().HasMaxLength(10).HasDefaultValueSql(@"''");
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.AREAMUELLE).HasColumnName(@"AREA_MUELLE").HasColumnType(@"char(6)").ValueGeneratedNever().HasMaxLength(6).HasDefaultValueSql(@"''");
            modelBuilder.Entity<MPOPEDC>().Property<decimal?>(x => x.OPERADOR).HasColumnName(@"OPERADOR").HasColumnType(@"numeric(5)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<MPOPEDC>().Property<System.DateTime?>(x => x.FCARGA).HasColumnName(@"F_CARGA").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<MPOPEDC>().Property<decimal?>(x => x.ORDENPRIO).HasColumnName(@"ORDEN_PRIO").HasColumnType(@"numeric(10)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.MOTIVOERR).HasColumnName(@"MOTIVO_ERR").HasColumnType(@"char(3)").ValueGeneratedNever().HasMaxLength(3).HasDefaultValueSql(@"''");
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.OBS).HasColumnName(@"OBS").HasColumnType(@"text").ValueGeneratedNever().HasMaxLength(2147483647).HasDefaultValueSql(@"''");
            modelBuilder.Entity<MPOPEDC>().Property<decimal?>(x => x.UNIDADES).HasColumnName(@"UNIDADES").HasColumnType(@"numeric(13,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<MPOPEDC>().Property<decimal?>(x => x.ITEMSPED).HasColumnName(@"ITEMS_PED").HasColumnType(@"numeric(12)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<MPOPEDC>().Property<string>(x => x.PROCESAR).HasColumnName(@"PROCESAR").HasColumnType(@"char(10)").ValueGeneratedNever().HasMaxLength(10).HasDefaultValueSql(@"''");
            modelBuilder.Entity<MPOPEDC>().Property<int?>(x => x.ORDEN).HasColumnName(@"ORDEN").HasColumnType(@"int").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<MPOPEDC>().Property<decimal?>(x => x.TOTKILOS).HasColumnName(@"TOT_KILOS").HasColumnType(@"numeric(12,2)").ValueGeneratedNever();
            modelBuilder.Entity<MPOPEDC>().Property<decimal?>(x => x.NRORUT).HasColumnName(@"NRO_RUT").HasColumnType(@"numeric(18)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<MPOPEDC>().HasKey(@"EMPLAZA", @"ALMACEN", @"TIPPEDIDO", @"CATPEDIDO", @"SUCPEDIDO", @"NROPEDIDO");
        }

        partial void CustomizeMPOPEDCMapping(ModelBuilder modelBuilder);

        #endregion

        #region MPOPEDD Mapping

        private void MPOPEDDMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MPOPEDD>().ToTable(@"MPOPEDD", @"dbo");
            modelBuilder.Entity<MPOPEDD>().Property<string>(x => x.EMPLAZA).HasColumnName(@"EMPLAZA").HasColumnType(@"char(3)").IsRequired().ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<MPOPEDD>().Property<string>(x => x.ALMACEN).HasColumnName(@"ALMACEN").HasColumnType(@"char(3)").IsRequired().ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<MPOPEDD>().Property<string>(x => x.TIPPEDIDO).HasColumnName(@"TIP_PEDIDO").HasColumnType(@"char(3)").IsRequired().ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<MPOPEDD>().Property<string>(x => x.CATPEDIDO).HasColumnName(@"CAT_PEDIDO").HasColumnType(@"char(1)").IsRequired().ValueGeneratedNever().HasMaxLength(1);
            modelBuilder.Entity<MPOPEDD>().Property<string>(x => x.SUCPEDIDO).HasColumnName(@"SUC_PEDIDO").HasColumnType(@"char(4)").IsRequired().ValueGeneratedNever().HasMaxLength(4);
            modelBuilder.Entity<MPOPEDD>().Property<decimal>(x => x.NROPEDIDO).HasColumnName(@"NRO_PEDIDO").HasColumnType(@"numeric(10)").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<MPOPEDD>().Property<decimal>(x => x.LINEA).HasColumnName(@"LINEA").HasColumnType(@"numeric(10)").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<MPOPEDD>().Property<string>(x => x.CIA).HasColumnName(@"CIA").HasColumnType(@"char(3)").IsRequired().ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<MPOPEDD>().Property<string>(x => x.PRODUCTO).HasColumnName(@"PRODUCTO").HasColumnType(@"char(15)").IsRequired().ValueGeneratedNever().HasMaxLength(15);
            modelBuilder.Entity<MPOPEDD>().Property<decimal>(x => x.CANTIDAD).HasColumnName(@"CANTIDAD").HasColumnType(@"numeric(13,2)").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<MPOPEDD>().Property<decimal?>(x => x.PU).HasColumnName(@"PU").HasColumnType(@"numeric(13,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<MPOPEDD>().Property<bool?>(x => x.DESPPARCI).HasColumnName(@"DESP_PARCI").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<MPOPEDD>().Property<System.DateTime?>(x => x.FVENC).HasColumnName(@"F_VENC").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"''");
            modelBuilder.Entity<MPOPEDD>().Property<string>(x => x.LOTE).HasColumnName(@"LOTE").HasColumnType(@"char(15)").ValueGeneratedNever().HasMaxLength(15).HasDefaultValueSql(@"''");
            modelBuilder.Entity<MPOPEDD>().Property<string>(x => x.SERIE).HasColumnName(@"SERIE").HasColumnType(@"char(15)").ValueGeneratedNever().HasMaxLength(15).HasDefaultValueSql(@"''");
            modelBuilder.Entity<MPOPEDD>().Property<bool?>(x => x.LOTEUNICO).HasColumnName(@"LOTE_UNICO").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<MPOPEDD>().Property<string>(x => x.MOTIVOERR).HasColumnName(@"MOTIVO_ERR").HasColumnType(@"char(3)").ValueGeneratedNever().HasMaxLength(3).HasDefaultValueSql(@"' '");
            modelBuilder.Entity<MPOPEDD>().Property<string>(x => x.ESTPROD).HasColumnName(@"EST_PROD").HasColumnType(@"char(3)").ValueGeneratedNever().HasMaxLength(3).HasDefaultValueSql(@"''");
            modelBuilder.Entity<MPOPEDD>().Property<decimal?>(x => x.PPP).HasColumnName(@"PPP").HasColumnType(@"numeric(12,4)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<MPOPEDD>().HasKey(@"EMPLAZA", @"ALMACEN", @"TIPPEDIDO", @"CATPEDIDO", @"SUCPEDIDO", @"NROPEDIDO", @"LINEA");
        }

        partial void CustomizeMPOPEDDMapping(ModelBuilder modelBuilder);

        #endregion

        #region TMCABPED Mapping

        private void TMCABPEDMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TMCABPED>().ToTable(@"TMCABPED", @"dbo");
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.EMPLAZA).HasColumnName(@"EMPLAZA").HasColumnType(@"char(3)").IsRequired().ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.ALMACEN).HasColumnName(@"ALMACEN").HasColumnType(@"char(3)").IsRequired().ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.TIPPEDIDO).HasColumnName(@"TIP_PEDIDO").HasColumnType(@"char(3)").IsRequired().ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.CATPEDIDO).HasColumnName(@"CAT_PEDIDO").HasColumnType(@"char(1)").IsRequired().ValueGeneratedNever().HasMaxLength(1);
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.SUCPEDIDO).HasColumnName(@"SUC_PEDIDO").HasColumnType(@"char(4)").IsRequired().ValueGeneratedNever().HasMaxLength(4);
            modelBuilder.Entity<TMCABPED>().Property<decimal>(x => x.NROPEDIDO).HasColumnName(@"NRO_PEDIDO").HasColumnType(@"numeric(10)").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<TMCABPED>().Property<System.DateTime>(x => x.FECHA).HasColumnName(@"FECHA").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.CLIENTE).HasColumnName(@"CLIENTE").HasColumnType(@"char(10)").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.SUBCLIENTE).HasColumnName(@"SUBCLIENTE").HasColumnType(@"char(10)").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.RAZONSOC).HasColumnName(@"RAZON_SOC").HasColumnType(@"char(60)").ValueGeneratedNever().HasMaxLength(60);
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.DOMICILIO).HasColumnName(@"DOMICILIO").HasColumnType(@"char(250)").ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.LOCALIDAD).HasColumnName(@"LOCALIDAD").HasColumnType(@"char(40)").ValueGeneratedNever().HasMaxLength(40);
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.PROVINCIA).HasColumnName(@"PROVINCIA").HasColumnType(@"char(30)").ValueGeneratedNever().HasMaxLength(30);
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.CP).HasColumnName(@"CP").HasColumnType(@"char(10)").ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<TMCABPED>().Property<bool>(x => x.PARTICIONA).HasColumnName(@"PARTICIONA").HasColumnType(@"bit").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<TMCABPED>().Property<System.DateTime?>(x => x.FENTREGA).HasColumnName(@"F_ENTREGA").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.REFA).HasColumnName(@"REF_A").HasColumnType(@"char(30)").ValueGeneratedNever().HasMaxLength(30);
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.REFB).HasColumnName(@"REF_B").HasColumnType(@"char(30)").ValueGeneratedNever().HasMaxLength(30);
            modelBuilder.Entity<TMCABPED>().Property<decimal?>(x => x.VALFACTUR).HasColumnName(@"VAL_FACTUR").HasColumnType(@"numeric(13,2)").ValueGeneratedNever();
            modelBuilder.Entity<TMCABPED>().Property<decimal?>(x => x.VALCONTRA).HasColumnName(@"VAL_CONTRA").HasColumnType(@"numeric(13,2)").ValueGeneratedNever();
            modelBuilder.Entity<TMCABPED>().Property<decimal?>(x => x.UNIDADES).HasColumnName(@"UNIDADES").HasColumnType(@"numeric(13,2)").ValueGeneratedNever();
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.CENCOS).HasColumnName(@"CENCOS").HasColumnType(@"char(10)").ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.AREAMUELLE).HasColumnName(@"AREA_MUELLE").HasColumnType(@"char(6)").ValueGeneratedNever().HasMaxLength(6);
            modelBuilder.Entity<TMCABPED>().Property<decimal?>(x => x.OPERADOR).HasColumnName(@"OPERADOR").HasColumnType(@"numeric(5)").ValueGeneratedNever();
            modelBuilder.Entity<TMCABPED>().Property<System.DateTime?>(x => x.FTRANSACC).HasColumnName(@"F_TRANSACC").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<TMCABPED>().Property<decimal?>(x => x.ORDENPRIO).HasColumnName(@"ORDEN_PRIO").HasColumnType(@"numeric(10)").ValueGeneratedNever();
            modelBuilder.Entity<TMCABPED>().Property<string>(x => x.OTROS).HasColumnName(@"OTROS").HasColumnType(@"char(7)").ValueGeneratedNever().HasMaxLength(7);
            modelBuilder.Entity<TMCABPED>().Property<decimal?>(x => x.ITEMSPED).HasColumnName(@"ITEMS_PED").HasColumnType(@"numeric(12)").ValueGeneratedNever();
            modelBuilder.Entity<TMCABPED>().Property<decimal>(x => x.ID).HasColumnName(@"ID").HasColumnType(@"numeric(18)").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<TMCABPED>().Property<decimal?>(x => x.PESOTOT).HasColumnName(@"PESO_TOT").HasColumnType(@"numeric(13,3)").ValueGeneratedNever();
            modelBuilder.Entity<TMCABPED>().HasKey(@"EMPLAZA", @"ALMACEN", @"TIPPEDIDO", @"CATPEDIDO", @"SUCPEDIDO", @"NROPEDIDO");
        }

        partial void CustomizeTMCABPEDMapping(ModelBuilder modelBuilder);

        #endregion

        #region RefreshToken Mapping

        private void RefreshTokenMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<RefreshToken>().ToTable(@"RefreshToken", @"dbo");
            modelBuilder.Entity<RefreshToken>().Property<int>(x => x.RefreshTokenId).HasColumnName(@"RefreshTokenId").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<RefreshToken>().Property<System.DateTime>(x => x.IssuedUtc).HasColumnName(@"IssuedUtc").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<RefreshToken>().Property<System.DateTime>(x => x.ExpiresUtc).HasColumnName(@"ExpiresUtc").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<RefreshToken>().Property<string>(x => x.Token).HasColumnName(@"Token").HasColumnType(@"varchar(250)").IsRequired().ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<RefreshToken>().Property<string>(x => x.CODIGOCLIENTE).HasColumnName(@"CODIGO_CLIENTE").HasColumnType(@"char(10)").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<RefreshToken>().Property<string>(x => x.USUARIOAPI).HasColumnName(@"USUARIO_API").HasColumnType(@"varchar(250)").IsRequired().ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<RefreshToken>().HasKey(@"RefreshTokenId");
        }

        partial void CustomizeRefreshTokenMapping(ModelBuilder modelBuilder);

        #endregion

        private void RelationshipsMapping(ModelBuilder modelBuilder) { }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
