//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 15/03/2019 11:55:31
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.ComponentModel;
using System.Reflection;
using System.Data.Common;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using BrainSystem.Pedidos.Model;
using BrainSystem.Pedidos.Model.SAADIS;
using static Dapper.SqlMapper;

namespace BrainSystem.Pedidos.DAL
{

    public partial class SaadisDBContext : DbContext
    {

        public SaadisDBContext() :
            base()
        {
            OnCreated();
        }

        public SaadisDBContext(DbContextOptions<SaadisDBContext> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                optionsBuilder.UseSqlServer(@"Data Source=.\sql2008;Initial Catalog=TCMasterDB;Integrated Security=True;Persist Security Info=True");
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);


        public virtual DbSet<CLIENTESACCESOAPI> CLIENTESACCESOAPIs
        {
            get;
            set;
        }

        public virtual DbSet<RECHRCA> RECHRCAs
        {
            get;
            set;
        }

        public virtual DbSet<RECHRDE> RECHRDEs
        {
            get;
            set;
        }

        public object CLIENTESACCESOAPI { get; set; }


        public virtual DbSet<RefreshToken> RefreshTokens
        {
            get;
            set;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //IMPORTANT: FOR EACH TYPE returned by a raw query or stored procedure we must "register" here the query 
            //modelBuilder.Query<DBName>();
            this.CLIENTESACCESOAPIMapping(modelBuilder);
            this.CustomizeCLIENTESACCESOAPIMapping(modelBuilder);

            this.RECHRCAMapping(modelBuilder);
            this.CustomizeRECHRCAMapping(modelBuilder);

            this.RECHRDEMapping(modelBuilder);
            this.CustomizeRECHRDEMapping(modelBuilder);

            this.RefreshTokenMapping(modelBuilder);
            this.CustomizeRefreshTokenMapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region CLIENTESACCESOAPI Mapping

        private void CLIENTESACCESOAPIMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CLIENTESACCESOAPI>().ToTable(@"CLIENTES_ACCESO_API", @"dbo");
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<string>(x => x.CODIGOCLIENTE).HasColumnName(@"CODIGO_CLIENTE").HasColumnType(@"char(10)").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<string>(x => x.USUARIOAPI).HasColumnName(@"USUARIO_API").HasColumnType(@"varchar(250)").IsRequired().ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<string>(x => x.PASSWORDAPI).HasColumnName(@"PASSWORD_API").HasColumnType(@"varchar(250)").IsRequired().ValueGeneratedNever().HasMaxLength(250);

            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<int?>(x => x.AccessFailedCount).HasColumnName(@"AccessFailedCount").HasColumnType(@"int").HasDefaultValue(0);
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<string>(x => x.ConcurrencyStamp).HasColumnName(@"ConcurrencyStamp").HasColumnType(@"nvarchar(36)");
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<string>(x => x.Email).HasColumnName(@"Email").HasColumnType(@"nvarchar(256)");
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<bool?>(x => x.EmailConfirmed).HasColumnName(@"EmailConfirmed").HasColumnType(@"bit").HasDefaultValue(false);
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<bool?>(x => x.LockoutEnabled).HasColumnName(@"LockoutEnabled").HasColumnType(@"bit").HasDefaultValue(true);
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<DateTimeOffset?>(x => x.LockoutEnd).HasColumnName(@"LockoutEnd").HasColumnType(@"datetimeoffset(7)");
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<string>(x => x.NormalizedEmail).HasColumnName(@"NormalizedEmail").HasColumnType(@"nvarchar(256)");
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<string>(x => x.NormalizedUserName).HasColumnName(@"NormalizedUserName").HasColumnType(@"nvarchar(256)");
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<string>(x => x.PasswordHash).HasColumnName(@"PasswordHash").HasColumnType(@"nvarchar(512)");
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<string>(x => x.PhoneNumber).HasColumnName(@"PhoneNumber").HasColumnType(@"nvarchar(15)");
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<bool?>(x => x.PhoneNumberConfirmed).HasColumnName(@"PhoneNumberConfirmed").HasColumnType(@"bit").HasDefaultValue(false);
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<string>(x => x.SecurityStamp).HasColumnName(@"SecurityStamp").HasColumnType(@"nvarchar(128)");
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<bool?>(x => x.TwoFactorEnabled).HasColumnName(@"TwoFactorEnabled").HasColumnType(@"bit").HasDefaultValue(false);
            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<string>(x => x.UserName).HasColumnName(@"UserName").HasColumnType(@"nvarchar(256)");

            modelBuilder.Entity<CLIENTESACCESOAPI>().Property<int>(x => x.Id).HasColumnName(@"Id").HasColumnType(@"int").ValueGeneratedOnAdd();

            modelBuilder.Entity<CLIENTESACCESOAPI>().HasKey(e => e.Id); // Set Id as the primary key

            //modelBuilder.Entity<CLIENTESACCESOAPI>().HasKey(@"CODIGOCLIENTE", @"USUARIOAPI");
        }

        partial void CustomizeCLIENTESACCESOAPIMapping(ModelBuilder modelBuilder);

        #endregion


        #region RefreshToken Mapping

        private void RefreshTokenMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<RefreshToken>().ToTable(@"RefreshToken", @"dbo");
            modelBuilder.Entity<RefreshToken>().Property<int>(x => x.RefreshTokenId).HasColumnName(@"RefreshTokenId").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<RefreshToken>().Property<System.DateTime>(x => x.IssuedUtc).HasColumnName(@"IssuedUtc").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<RefreshToken>().Property<System.DateTime>(x => x.ExpiresUtc).HasColumnName(@"ExpiresUtc").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<RefreshToken>().Property<string>(x => x.Token).HasColumnName(@"Token").HasColumnType(@"varchar(250)").IsRequired().ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<RefreshToken>().Property<string>(x => x.CODIGOCLIENTE).HasColumnName(@"CODIGO_CLIENTE").HasColumnType(@"char(10)").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<RefreshToken>().Property<string>(x => x.USUARIOAPI).HasColumnName(@"USUARIO_API").HasColumnType(@"varchar(250)").IsRequired().ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<RefreshToken>().HasKey(@"RefreshTokenId");
        }

        partial void CustomizeRefreshTokenMapping(ModelBuilder modelBuilder);

        #endregion

        #region RECHRCA Mapping

        private void RECHRCAMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<RECHRCA>().ToTable(@"RECHRCA", @"dbo");
            modelBuilder.Entity<RECHRCA>().Property<string>(x => x.RHRNROHRU).HasColumnName(@"RHR_NROHRU").HasColumnType(@"char(12)").IsRequired().ValueGeneratedNever().HasMaxLength(12).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRCA>().Property<System.Nullable<System.DateTime>>(x => x.RHRFERECE).HasColumnName(@"RHR_FERECE").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRCA>().Property<System.Nullable<decimal>>(x => x.RHRCANCBT).HasColumnName(@"RHR_CANCBT").HasColumnType(@"numeric(5)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRCA>().Property<System.Nullable<System.DateTime>>(x => x.RHRFEPROC).HasColumnName(@"RHR_FEPROC").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRCA>().Property<string>(x => x.RHRFLETER).HasColumnName(@"RHR_FLETER").HasColumnType(@"char(5)").ValueGeneratedNever().HasMaxLength(5).HasDefaultValueSql(@"' '");
            modelBuilder.Entity<RECHRCA>().Property<System.Nullable<bool>>(x => x.RHROK).HasColumnName(@"RHR_OK").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRCA>().HasKey(@"RHRNROHRU");
        }

        partial void CustomizeRECHRCAMapping(ModelBuilder modelBuilder);

        #endregion


        #region RECHRDE Mapping

        private void RECHRDEMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<RECHRDE>().ToTable(@"RECHRDE", @"dbo");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTCENEMI).HasColumnName(@"CBT_CENEMI").HasColumnType(@"char(4)").IsRequired().ValueGeneratedNever().HasMaxLength(4).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTNROCBT).HasColumnName(@"CBT_NROCBT").HasColumnType(@"char(8)").IsRequired().ValueGeneratedNever().HasMaxLength(8).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTLETCBT).HasColumnName(@"CBT_LETCBT").HasColumnType(@"char(1)").IsRequired().ValueGeneratedNever().HasMaxLength(1).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.RHDNROCLI).HasColumnName(@"RHD_NROCLI").HasColumnType(@"char(10)").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTCODCBT).HasColumnName(@"CBT_CODCBT").HasColumnType(@"char(2)").IsRequired().ValueGeneratedNever().HasMaxLength(2);
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<System.DateTime>>(x => x.CBTFECCBT).HasColumnName(@"CBT_FECCBT").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTZONADE).HasColumnName(@"CBT_ZONADE").HasColumnType(@"char(4)").ValueGeneratedNever().HasMaxLength(4).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTLINEDE).HasColumnName(@"CBT_LINEDE").HasColumnType(@"char(2)").ValueGeneratedNever().HasMaxLength(2).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTREMITO).HasColumnName(@"CBT_REMITO").HasColumnType(@"char(15)").ValueGeneratedNever().HasMaxLength(15).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTBULTOS).HasColumnName(@"CBT_BULTOS").HasColumnType(@"numeric(7,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTKILOSN).HasColumnName(@"CBT_KILOSN").HasColumnType(@"numeric(10,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTKILOSA).HasColumnName(@"CBT_KILOSA").HasColumnType(@"numeric(10,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTMETRCB).HasColumnName(@"CBT_METRCB").HasColumnType(@"numeric(15,4)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTNOMRTE).HasColumnName(@"CBT_NOMRTE").HasColumnType(@"char(30)").ValueGeneratedNever().HasMaxLength(30).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTLOCRTE).HasColumnName(@"CBT_LOCRTE").HasColumnType(@"char(30)").ValueGeneratedNever().HasMaxLength(30).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTSUBCLI).HasColumnName(@"CBT_SUBCLI").HasColumnType(@"char(10)").ValueGeneratedNever().HasMaxLength(10).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTNOMDES).HasColumnName(@"CBT_NOMDES").HasColumnType(@"char(30)").ValueGeneratedNever().HasMaxLength(30).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTDOMDES).HasColumnName(@"CBT_DOMDES").HasColumnType(@"char(30)").ValueGeneratedNever().HasMaxLength(30).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTLOCDES).HasColumnName(@"CBT_LOCDES").HasColumnType(@"char(20)").ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTNRODES).HasColumnName(@"CBT_NRODES").HasColumnType(@"char(5)").ValueGeneratedNever().HasMaxLength(5).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTDTODES).HasColumnName(@"CBT_DTODES").HasColumnType(@"char(5)").ValueGeneratedNever().HasMaxLength(5).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.LCLCPOSTA).HasColumnName(@"LCL_CPOSTA").HasColumnType(@"char(10)").ValueGeneratedNever().HasMaxLength(10).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTNROHRU).HasColumnName(@"CBT_NROHRU").HasColumnType(@"char(12)").ValueGeneratedNever().HasMaxLength(12).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTVADESE).HasColumnName(@"CBT_VADESE").HasColumnType(@"numeric(15,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTNROCRE).HasColumnName(@"CBT_NROCRE").HasColumnType(@"char(7)").ValueGeneratedNever().HasMaxLength(7).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIMPCRE).HasColumnName(@"CBT_IMPCRE").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTFLETET).HasColumnName(@"CBT_FLETET").HasColumnType(@"numeric(11,2)").ValueGeneratedNever();
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIMPSEG).HasColumnName(@"CBT_IMPSEG").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIMPRET).HasColumnName(@"CBT_IMPRET").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIMPENT).HasColumnName(@"CBT_IMPENT").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIMPOTR).HasColumnName(@"CBT_IMPOTR").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIMPIVA).HasColumnName(@"CBT_IMPIVA").HasColumnType(@"numeric(11,2)").ValueGeneratedNever();
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIIVAAD).HasColumnName(@"CBT_IIVAAD").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIMPBON).HasColumnName(@"CBT_IMPBON").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.IVACODIGO).HasColumnName(@"IVA_CODIGO").HasColumnType(@"char(1)").ValueGeneratedNever().HasMaxLength(1).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CLTCUIT).HasColumnName(@"CLT_CUIT").HasColumnType(@"char(13)").ValueGeneratedNever().HasMaxLength(13).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTPICKIN).HasColumnName(@"CBT_PICKIN").HasColumnType(@"numeric(12)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTDESCRI).HasColumnName(@"CBT_DESCRI").HasColumnType(@"char(30)").ValueGeneratedNever().HasMaxLength(30).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtTIPPED).HasColumnName(@"Cbt_TIPPED").HasColumnType(@"char(3)").ValueGeneratedNever().HasMaxLength(3).HasDefaultValueSql(@"' '");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTPALLET).HasColumnName(@"CBT_PALLET").HasColumnType(@"numeric(7,2)").ValueGeneratedNever().HasDefaultValueSql(@"0.00");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTUNIDAD).HasColumnName(@"CBT_UNIDAD").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<System.DateTime>>(x => x.CBTFEPOEN).HasColumnName(@"CBT_FEPOEN").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTDESCR2).HasColumnName(@"CBT_DESCR2").HasColumnType(@"char(33)").ValueGeneratedNever().HasMaxLength(33).HasDefaultValueSql(@"' '");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTVDCR).HasColumnName(@"CBT_VDCR").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTSUCORI).HasColumnName(@"CBT_SUCORI").HasColumnType(@"char(4)").ValueGeneratedNever().HasMaxLength(4);
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtTivade).HasColumnName(@"cbt_tivade").HasColumnType(@"char(1)").ValueGeneratedNever().HasMaxLength(1).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtCuitde).HasColumnName(@"cbt_cuitde").HasColumnType(@"char(13)").ValueGeneratedNever().HasMaxLength(13).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtFleasi).HasColumnName(@"cbt_fleasi").HasColumnType(@"char(5)").ValueGeneratedNever().HasMaxLength(5).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtVehasi).HasColumnName(@"cbt_vehasi").HasColumnType(@"char(3)").ValueGeneratedNever().HasMaxLength(3).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CbtSecuhr).HasColumnName(@"Cbt_secuhr").HasColumnType(@"numeric(4)").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTDETALL).HasColumnName(@"CBT_DETALL").HasColumnType(@"text").IsRequired().ValueGeneratedNever().HasMaxLength(2147483647).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTEMAIL).HasColumnName(@"CBT_EMAIL").HasColumnType(@"char(100)").ValueGeneratedNever().HasMaxLength(100).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<bool>(x => x.ESCANEADO).HasColumnName(@"ESCANEADO").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtTelefo).HasColumnName(@"Cbt_telefo").HasColumnType(@"char(70)").ValueGeneratedNever().HasMaxLength(70).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtAdic1).HasColumnName(@"Cbt_adic1").HasColumnType(@"char(80)").ValueGeneratedNever().HasMaxLength(80).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtAdic2).HasColumnName(@"Cbt_adic2").HasColumnType(@"char(80)").ValueGeneratedNever().HasMaxLength(80).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtAdic3).HasColumnName(@"Cbt_adic3").HasColumnType(@"char(80)").ValueGeneratedNever().HasMaxLength(80).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtAdic4).HasColumnName(@"Cbt_adic4").HasColumnType(@"char(50)").ValueGeneratedNever().HasMaxLength(50).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtAdic5).HasColumnName(@"Cbt_adic5").HasColumnType(@"char(50)").ValueGeneratedNever().HasMaxLength(50).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtSenasa).HasColumnName(@"Cbt_senasa").HasColumnType(@"char(1)").ValueGeneratedNever().HasMaxLength(1).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CbtImpad1).HasColumnName(@"Cbt_impad1").HasColumnType(@"numeric(15,2)").ValueGeneratedNever().HasDefaultValueSql(@"0.00");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CbtImpad2).HasColumnName(@"Cbt_impad2").HasColumnType(@"numeric(15,2)").ValueGeneratedNever().HasDefaultValueSql(@"0.00");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CbtAbasto).HasColumnName(@"Cbt_abasto").HasColumnType(@"numeric(15,2)").ValueGeneratedNever().HasDefaultValueSql(@"0.00");
            modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CbtPercib).HasColumnName(@"Cbt_percib").HasColumnType(@"numeric(15,2)").ValueGeneratedNever().HasDefaultValueSql(@"0.00");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtTipcar).HasColumnName(@"Cbt_tipcar").HasColumnType(@"char(3)").ValueGeneratedNever().HasMaxLength(3).HasDefaultValueSql(@"''");
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtNomdesAlter).HasColumnName(@"Cbt_nomdes_alter").HasColumnType(@"char(40)").ValueGeneratedNever().HasMaxLength(40);
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtTivadeAlter).HasColumnName(@"Cbt_tivade_alter").HasColumnType(@"char(1)").ValueGeneratedNever().HasMaxLength(1);
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtCuitdeAlter).HasColumnName(@"Cbt_cuitde_alter").HasColumnType(@"char(13)").ValueGeneratedNever().HasMaxLength(13);
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtTelefoAlter).HasColumnName(@"Cbt_telefo_alter").HasColumnType(@"char(70)").ValueGeneratedNever().HasMaxLength(70);
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtCodVerif).HasColumnName(@"Cbt_codVerif").HasColumnType(@"varchar(500)").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtDatosEntrega).HasColumnName(@"Cbt_DatosEntrega").HasColumnType(@"varchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<RECHRDE>().HasKey(@"RHDNROCLI", @"CBTCODCBT", @"CBTCENEMI", @"CBTNROCBT", @"CBTLETCBT");
        }

        partial void CustomizeRECHRDEMapping(ModelBuilder modelBuilder);

        #endregion

        /*
                #region RECHRDE Mapping

                private void RECHRDEMapping(ModelBuilder modelBuilder)
                {
                    modelBuilder.Entity<RECHRDE>().ToTable(@"RECHRDE", @"dbo");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTCENEMI).HasColumnName(@"CBT_CENEMI").HasColumnType(@"char(4)").IsRequired().ValueGeneratedNever().HasMaxLength(4).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTNROCBT).HasColumnName(@"CBT_NROCBT").HasColumnType(@"char(8)").IsRequired().ValueGeneratedNever().HasMaxLength(8).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTLETCBT).HasColumnName(@"CBT_LETCBT").HasColumnType(@"char(1)").IsRequired().ValueGeneratedNever().HasMaxLength(1).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.RHDNROCLI).HasColumnName(@"RHD_NROCLI").HasColumnType(@"char(10)").IsRequired().ValueGeneratedNever().HasMaxLength(10);
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTCODCBT).HasColumnName(@"CBT_CODCBT").HasColumnType(@"char(2)").IsRequired().ValueGeneratedNever().HasMaxLength(2);
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<System.DateTime>>(x => x.CBTFECCBT).HasColumnName(@"CBT_FECCBT").HasColumnType(@"datetime").ValueGeneratedNever();
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTZONADE).HasColumnName(@"CBT_ZONADE").HasColumnType(@"char(4)").ValueGeneratedNever().HasMaxLength(4).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTLINEDE).HasColumnName(@"CBT_LINEDE").HasColumnType(@"char(2)").ValueGeneratedNever().HasMaxLength(2).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTREMITO).HasColumnName(@"CBT_REMITO").HasColumnType(@"char(15)").ValueGeneratedNever().HasMaxLength(15).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTBULTOS).HasColumnName(@"CBT_BULTOS").HasColumnType(@"numeric(7,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTKILOSN).HasColumnName(@"CBT_KILOSN").HasColumnType(@"numeric(7,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTKILOSA).HasColumnName(@"CBT_KILOSA").HasColumnType(@"numeric(7,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTMETRCB).HasColumnName(@"CBT_METRCB").HasColumnType(@"numeric(7,4)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTNOMRTE).HasColumnName(@"CBT_NOMRTE").HasColumnType(@"char(30)").ValueGeneratedNever().HasMaxLength(30).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTLOCRTE).HasColumnName(@"CBT_LOCRTE").HasColumnType(@"char(30)").ValueGeneratedNever().HasMaxLength(30).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTSUBCLI).HasColumnName(@"CBT_SUBCLI").HasColumnType(@"char(10)").ValueGeneratedNever().HasMaxLength(10).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTNOMDES).HasColumnName(@"CBT_NOMDES").HasColumnType(@"char(30)").ValueGeneratedNever().HasMaxLength(30).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTDOMDES).HasColumnName(@"CBT_DOMDES").HasColumnType(@"char(30)").ValueGeneratedNever().HasMaxLength(30).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTLOCDES).HasColumnName(@"CBT_LOCDES").HasColumnType(@"char(20)").ValueGeneratedNever().HasMaxLength(20);
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTNRODES).HasColumnName(@"CBT_NRODES").HasColumnType(@"char(5)").ValueGeneratedNever().HasMaxLength(5);
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTDTODES).HasColumnName(@"CBT_DTODES").HasColumnType(@"char(5)").ValueGeneratedNever().HasMaxLength(5);
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.LCLCPOSTA).HasColumnName(@"LCL_CPOSTA").HasColumnType(@"char(10)").ValueGeneratedNever().HasMaxLength(10).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTNROHRU).HasColumnName(@"CBT_NROHRU").HasColumnType(@"char(12)").ValueGeneratedNever().HasMaxLength(12).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTVADESE).HasColumnName(@"CBT_VADESE").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTNROCRE).HasColumnName(@"CBT_NROCRE").HasColumnType(@"char(7)").ValueGeneratedNever().HasMaxLength(7).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIMPCRE).HasColumnName(@"CBT_IMPCRE").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTFLETET).HasColumnName(@"CBT_FLETET").HasColumnType(@"numeric(11,2)").ValueGeneratedNever();
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIMPSEG).HasColumnName(@"CBT_IMPSEG").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIMPRET).HasColumnName(@"CBT_IMPRET").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIMPENT).HasColumnName(@"CBT_IMPENT").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIMPOTR).HasColumnName(@"CBT_IMPOTR").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIMPIVA).HasColumnName(@"CBT_IMPIVA").HasColumnType(@"numeric(11,2)").ValueGeneratedNever();
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIIVAAD).HasColumnName(@"CBT_IIVAAD").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTIMPBON).HasColumnName(@"CBT_IMPBON").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.IVACODIGO).HasColumnName(@"IVA_CODIGO").HasColumnType(@"char(1)").ValueGeneratedNever().HasMaxLength(1).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CLTCUIT).HasColumnName(@"CLT_CUIT").HasColumnType(@"char(13)").ValueGeneratedNever().HasMaxLength(13).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTPICKIN).HasColumnName(@"CBT_PICKIN").HasColumnType(@"numeric(12)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTDESCRI).HasColumnName(@"CBT_DESCRI").HasColumnType(@"char(30)").ValueGeneratedNever().HasMaxLength(30).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtTIPPED).HasColumnName(@"Cbt_TIPPED").HasColumnType(@"char(3)").ValueGeneratedNever().HasMaxLength(3).HasDefaultValueSql(@"' '");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTPALLET).HasColumnName(@"CBT_PALLET").HasColumnType(@"numeric(7,2)").ValueGeneratedNever().HasDefaultValueSql(@"0.00");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTUNIDAD).HasColumnName(@"CBT_UNIDAD").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<System.DateTime>>(x => x.CBTFEPOEN).HasColumnName(@"CBT_FEPOEN").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTDESCR2).HasColumnName(@"CBT_DESCR2").HasColumnType(@"char(33)").ValueGeneratedNever().HasMaxLength(33).HasDefaultValueSql(@"' '");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CBTVDCR).HasColumnName(@"CBT_VDCR").HasColumnType(@"numeric(11,2)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CBTSUCORI).HasColumnName(@"CBT_SUCORI").HasColumnType(@"char(4)").ValueGeneratedNever().HasMaxLength(4);
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtTivade).HasColumnName(@"cbt_tivade").HasColumnType(@"char(1)").ValueGeneratedNever().HasMaxLength(1).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtCuitde).HasColumnName(@"cbt_cuitde").HasColumnType(@"char(13)").ValueGeneratedNever().HasMaxLength(13).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtFleasi).HasColumnName(@"cbt_fleasi").HasColumnType(@"char(5)").ValueGeneratedNever().HasMaxLength(5).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<string>(x => x.CbtVehasi).HasColumnName(@"cbt_vehasi").HasColumnType(@"char(3)").ValueGeneratedNever().HasMaxLength(3).HasDefaultValueSql(@"''");
                    modelBuilder.Entity<RECHRDE>().Property<System.Nullable<decimal>>(x => x.CbtSecuhr).HasColumnName(@"Cbt_secuhr").HasColumnType(@"numeric(4)").ValueGeneratedNever().HasDefaultValueSql(@"0");
                    modelBuilder.Entity<RECHRDE>().HasKey(@"RHDNROCLI", @"CBTCODCBT", @"CBTCENEMI", @"CBTNROCBT", @"CBTLETCBT");
                }

                partial void CustomizeRECHRDEMapping(ModelBuilder modelBuilder);

                #endregion
        */
        private void RelationshipsMapping(ModelBuilder modelBuilder) { }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
