//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 02/05/2019 11:34:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;

namespace BrainSystem.Pedidos.Model
{
    public partial class CLIENTESACCESOAPI : IdentityUser
    {

        public CLIENTESACCESOAPI()
        {
            OnCreated();
        }

        public int Id { get; set; }

        public virtual string CODIGOCLIENTE
        {
            get;
            set;
        }

        public virtual string USUARIOAPI
        {
            get;
            set;
        }

        public virtual string PASSWORDAPI
        {
            get;
            set;
        }

        public virtual string CODIGO_CIA
        {
            get;
            set;
        }

        public int AccessFailedCount { get; set; }
        public string ConcurrencyStamp { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public bool LockoutEnabled { get; set; }
        public DateTimeOffset? LockoutEnd { get; set; }
        public string NormalizedEmail { get; set; }
        public string NormalizedUserName { get; set; }
        public string PasswordHash { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public string SecurityStamp { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public string UserName { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
