//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 02/05/2019 11:34:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace BrainSystem.Pedidos.Model
{
    public partial class MPOPEDC {

        public MPOPEDC()
        {
            this.REFA = @"";
            this.REFB = @"";
            this.CENCOS = @"";
            this.AREAMUELLE = @"";
            this.OPERADOR = 0m;
            this.ORDENPRIO = 0m;
            this.MOTIVOERR = @"";
            this.OBS = @"";
            this.UNIDADES = 0m;
            this.ITEMSPED = 0m;
            this.PROCESAR = @"";
            this.ORDEN = 0;
            this.NRORUT = 0m;
            OnCreated();
        }

        public virtual string EMPLAZA
        {
            get;
            set;
        }

        public virtual string ALMACEN
        {
            get;
            set;
        }

        public virtual string TIPPEDIDO
        {
            get;
            set;
        }

        public virtual string CATPEDIDO
        {
            get;
            set;
        }

        public virtual string SUCPEDIDO
        {
            get;
            set;
        }

        public virtual decimal NROPEDIDO
        {
            get;
            set;
        }

        public virtual System.DateTime FECHA
        {
            get;
            set;
        }

        public virtual string CLIENTE
        {
            get;
            set;
        }

        public virtual string SUBCLIENTE
        {
            get;
            set;
        }

        public virtual string RAZONSOC
        {
            get;
            set;
        }

        public virtual string DOMICILIO
        {
            get;
            set;
        }

        public virtual string LOCALIDAD
        {
            get;
            set;
        }

        public virtual string PROVINCIA
        {
            get;
            set;
        }

        public virtual string CP
        {
            get;
            set;
        }

        public virtual bool PARTICIONA
        {
            get;
            set;
        }

        public virtual System.DateTime FENTREGA
        {
            get;
            set;
        }

        public virtual string REFA
        {
            get;
            set;
        }

        public virtual string REFB
        {
            get;
            set;
        }

        public virtual decimal VALFACTUR
        {
            get;
            set;
        }

        public virtual decimal VALCONTRA
        {
            get;
            set;
        }

        public virtual string CENCOS
        {
            get;
            set;
        }

        public virtual string AREAMUELLE
        {
            get;
            set;
        }

        public virtual decimal? OPERADOR
        {
            get;
            set;
        }

        public virtual System.DateTime? FCARGA
        {
            get;
            set;
        }

        public virtual decimal? ORDENPRIO
        {
            get;
            set;
        }

        public virtual string MOTIVOERR
        {
            get;
            set;
        }

        public virtual string OBS
        {
            get;
            set;
        }

        public virtual decimal? UNIDADES
        {
            get;
            set;
        }

        public virtual decimal? ITEMSPED
        {
            get;
            set;
        }

        public virtual string PROCESAR
        {
            get;
            set;
        }

        public virtual int? ORDEN
        {
            get;
            set;
        }

        public virtual decimal? TOTKILOS
        {
            get;
            set;
        }

        public virtual decimal? NRORUT
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          MPOPEDC toCompare = obj as MPOPEDC;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.EMPLAZA, toCompare.EMPLAZA))
            return false;
          if (!Object.Equals(this.ALMACEN, toCompare.ALMACEN))
            return false;
          if (!Object.Equals(this.TIPPEDIDO, toCompare.TIPPEDIDO))
            return false;
          if (!Object.Equals(this.CATPEDIDO, toCompare.CATPEDIDO))
            return false;
          if (!Object.Equals(this.SUCPEDIDO, toCompare.SUCPEDIDO))
            return false;
          if (!Object.Equals(this.NROPEDIDO, toCompare.NROPEDIDO))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + EMPLAZA.GetHashCode();
          hashCode = (hashCode * 7) + ALMACEN.GetHashCode();
          hashCode = (hashCode * 7) + TIPPEDIDO.GetHashCode();
          hashCode = (hashCode * 7) + CATPEDIDO.GetHashCode();
          hashCode = (hashCode * 7) + SUCPEDIDO.GetHashCode();
          hashCode = (hashCode * 7) + NROPEDIDO.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
