//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 02/05/2019 11:34:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace BrainSystem.Pedidos.Model
{
    public partial class MPOPEDD {

        public MPOPEDD()
        {
            this.PU = 0m;
            this.LOTE = @"";
            this.SERIE = @"";
            this.MOTIVOERR = @" ";
            this.ESTPROD = @"";
            this.PPP = 0m;
            OnCreated();
        }

        public virtual string EMPLAZA
        {
            get;
            set;
        }

        public virtual string ALMACEN
        {
            get;
            set;
        }

        public virtual string TIPPEDIDO
        {
            get;
            set;
        }

        public virtual string CATPEDIDO
        {
            get;
            set;
        }

        public virtual string SUCPEDIDO
        {
            get;
            set;
        }

        public virtual decimal NROPEDIDO
        {
            get;
            set;
        }

        public virtual decimal LINEA
        {
            get;
            set;
        }

        public virtual string CIA
        {
            get;
            set;
        }

        public virtual string PRODUCTO
        {
            get;
            set;
        }

        public virtual decimal CANTIDAD
        {
            get;
            set;
        }

        public virtual decimal? PU
        {
            get;
            set;
        }

        public virtual bool? DESPPARCI
        {
            get;
            set;
        }

        public virtual System.DateTime? FVENC
        {
            get;
            set;
        }

        public virtual string LOTE
        {
            get;
            set;
        }

        public virtual string SERIE
        {
            get;
            set;
        }

        public virtual bool? LOTEUNICO
        {
            get;
            set;
        }

        public virtual string MOTIVOERR
        {
            get;
            set;
        }

        public virtual string ESTPROD
        {
            get;
            set;
        }

        public virtual decimal? PPP
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          MPOPEDD toCompare = obj as MPOPEDD;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.EMPLAZA, toCompare.EMPLAZA))
            return false;
          if (!Object.Equals(this.ALMACEN, toCompare.ALMACEN))
            return false;
          if (!Object.Equals(this.TIPPEDIDO, toCompare.TIPPEDIDO))
            return false;
          if (!Object.Equals(this.CATPEDIDO, toCompare.CATPEDIDO))
            return false;
          if (!Object.Equals(this.SUCPEDIDO, toCompare.SUCPEDIDO))
            return false;
          if (!Object.Equals(this.NROPEDIDO, toCompare.NROPEDIDO))
            return false;
          if (!Object.Equals(this.LINEA, toCompare.LINEA))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + EMPLAZA.GetHashCode();
          hashCode = (hashCode * 7) + ALMACEN.GetHashCode();
          hashCode = (hashCode * 7) + TIPPEDIDO.GetHashCode();
          hashCode = (hashCode * 7) + CATPEDIDO.GetHashCode();
          hashCode = (hashCode * 7) + SUCPEDIDO.GetHashCode();
          hashCode = (hashCode * 7) + NROPEDIDO.GetHashCode();
          hashCode = (hashCode * 7) + LINEA.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
