//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 31/7/2018 12:26:55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BrainSystem.Pedidos.Model
{
    public partial class RefreshToken {

        public RefreshToken()
        {
            OnCreated();
        }

        public virtual int RefreshTokenId
        {
            get;
            set;
        }

        public virtual System.DateTime IssuedUtc
        {
            get;
            set;
        }

        public virtual System.DateTime ExpiresUtc
        {
            get;
            set;
        }

        public virtual string Token
        {
            get;
            set;
        }

        public virtual string CODIGOCLIENTE
        {
            get;
            set;
        }

        public virtual string USUARIOAPI
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
