//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 08/05/2019 18:21:40
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace BrainSystem.Pedidos.Model
{
    public partial class SUBCLIEN
    {

        public SUBCLIEN()
        {
             OnCreated();
        }

        public virtual string CLIENTE
        {
            get;
            set;
        }

        public virtual string CODIGO
        {
            get;
            set;
        }

        public virtual string RAZONSOC
        {
            get;
            set;
        }

        public virtual string DOMICILIO
        {
            get;
            set;
        }

        public virtual string LOCALIDAD
        {
            get;
            set;
        }

        public virtual string PROVINCIA
        {
            get;
            set;
        }

        public virtual string CP
        {
            get;
            set;
        }

        public virtual string IVA
        {
            get;
            set;
        }

        public virtual string CUIT
        {
            get;
            set;
        }

        public virtual string TARVIS
        {
            get;
            set;
        }

        public virtual string METVAL
        {
            get;
            set;
        }

        public virtual string METFAC
        {
            get;
            set;
        }

        public virtual string CONCOM
        {
            get;
            set;
        }

        public virtual string METAFO
        {
            get;
            set;
        }

        public virtual string CODVAL
        {
            get;
            set;
        }

        public virtual string TARCAR
        {
            get;
            set;
        }

        public virtual string TELEFONO
        {
            get;
            set;
        }

        public virtual string FAX
        {
            get;
            set;
        }

        public virtual string ZONA
        {
            get;
            set;
        }

        public virtual string VENDEDOR
        {
            get;
            set;
        }

        public virtual string AREAMUELLE
        {
            get;
            set;
        }

        public virtual decimal? DIASVTO
        {
            get;
            set;
        }

        public virtual string PAIS
        {
            get;
            set;
        }

        public virtual string RESERVA
        {
            get;
            set;
        }

        public virtual decimal? PPICK
        {
            get;
            set;
        }

        public virtual string HEDESDE
        {
            get;
            set;
        }

        public virtual string HEHASTA
        {
            get;
            set;
        }

        public virtual string NRORUC
        {
            get;
            set;
        }

        public virtual string FEDESDE
        {
            get;
            set;
        }

        public virtual string FEHASTA
        {
            get;
            set;
        }

        public virtual string CONTACTO
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
            SUBCLIEN toCompare = obj as SUBCLIEN;
            if (toCompare == null)
            {
                return false;
            }

            if (!Object.Equals(this.CLIENTE, toCompare.CLIENTE))
                return false;
            if (!Object.Equals(this.CODIGO, toCompare.CODIGO))
                return false;

            return true;
        }

        public override int GetHashCode()
        {
            int hashCode = 13;
            hashCode = (hashCode * 7) + CLIENTE.GetHashCode();
            hashCode = (hashCode * 7) + CODIGO.GetHashCode();
            return hashCode;
        }

        #endregion
    }

}
