//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 02/05/2019 11:34:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace BrainSystem.Pedidos.Model
{
    public partial class TMDETPED {

        public TMDETPED()
        {
            this.KILOS = 0m;
            OnCreated();
        }

        public virtual string EMPLAZA
        {
            get;
            set;
        }

        public virtual string ALMACEN
        {
            get;
            set;
        }

        public virtual string TIPPEDIDO
        {
            get;
            set;
        }

        public virtual string CATPEDIDO
        {
            get;
            set;
        }

        public virtual string SUCPEDIDO
        {
            get;
            set;
        }

        public virtual decimal? NROPEDIDO
        {
            get;
            set;
        }

        public virtual decimal LINEA
        {
            get;
            set;
        }

        public virtual string CIA
        {
            get;
            set;
        }

        public virtual string PRODUCTO
        {
            get;
            set;
        }

        public virtual decimal? CANTIDAD
        {
            get;
            set;
        }

        public virtual string LOTEUNICO
        {
            get;
            set;
        }

        public virtual string DESPPARCI
        {
            get;
            set;
        }

        public virtual string LOTE
        {
            get;
            set;
        }

        public virtual string SERIE
        {
            get;
            set;
        }

        public virtual decimal ID
        {
            get;
            set;
        }

        public virtual string ESTPROD
        {
            get;
            set;
        }

        public virtual decimal KILOS
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
