//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 16/04/2021 17:51:20
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace BrainSystem.Pedidos.Model.SAADIS
{
    public partial class RECHRCA {

        public RECHRCA()
        {
            this.RHRNROHRU = @"";
            this.RHRCANCBT = 0m;
            this.RHRFLETER = @" ";
            OnCreated();
        }

        public virtual string RHRNROHRU
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> RHRFERECE
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> RHRCANCBT
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> RHRFEPROC
        {
            get;
            set;
        }

        public virtual string RHRFLETER
        {
            get;
            set;
        }

        public virtual System.Nullable<bool> RHROK
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
