//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 16/04/2021 17:51:20
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace BrainSystem.Pedidos.Model.SAADIS
{
    public partial class RECHRDE {

        public RECHRDE()
        {
            this.CBTCENEMI = @"";
            this.CBTNROCBT = @"";
            this.CBTLETCBT = @"";
            this.CBTZONADE = @"";
            this.CBTLINEDE = @"";
            this.CBTREMITO = @"";
            this.CBTBULTOS = 0m;
            this.CBTKILOSN = 0m;
            this.CBTKILOSA = 0m;
            this.CBTMETRCB = 0m;
            this.CBTNOMRTE = @"";
            this.CBTLOCRTE = @"";
            this.CBTSUBCLI = @"";
            this.CBTNOMDES = @"";
            this.CBTDOMDES = @"";
            this.CBTNRODES = @"";
            this.CBTDTODES = @"";
            this.LCLCPOSTA = @"";
            this.CBTNROHRU = @"";
            this.CBTVADESE = 0m;
            this.CBTNROCRE = @"";
            this.CBTIMPCRE = 0m;
            this.CBTIMPSEG = 0m;
            this.CBTIMPRET = 0m;
            this.CBTIMPENT = 0m;
            this.CBTIMPOTR = 0m;
            this.CBTIIVAAD = 0m;
            this.CBTIMPBON = 0m;
            this.IVACODIGO = @"";
            this.CLTCUIT = @"";
            this.CBTPICKIN = 0m;
            this.CBTDESCRI = @"";
            this.CbtTIPPED = @" ";
            this.CBTPALLET = 0.00m;
            this.CBTUNIDAD = 0m;
            this.CBTDESCR2 = @" ";
            this.CBTVDCR = 0m;
            this.CbtTivade = @"";
            this.CbtCuitde = @"";
            this.CbtFleasi = @"";
            this.CbtVehasi = @"";
            this.CbtSecuhr = 0m;
            this.CBTDETALL = @"";
            this.CBTEMAIL = @"";
            this.CbtTelefo = @"";
            this.CbtAdic1 = @"";
            this.CbtAdic2 = @"";
            this.CbtAdic3 = @"";
            this.CbtAdic4 = @"";
            this.CbtAdic5 = @"";
            this.CbtSenasa = @"";
            this.CbtImpad1 = 0.00m;
            this.CbtImpad2 = 0.00m;
            this.CbtAbasto = 0.00m;
            this.CbtPercib = 0.00m;
            this.CbtTipcar = @"";

            OnCreated();
        }


        public virtual string CBTCENEMI
        {
            get;
            set;
        }

        public virtual string CBTNROCBT
        {
            get;
            set;
        }

        public virtual string CBTLETCBT
        {
            get;
            set;
        }

        public virtual string RHDNROCLI
        {
            get;
            set;
        }

        public virtual string CBTCODCBT
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> CBTFECCBT
        {
            get;
            set;
        }

        public virtual string CBTZONADE
        {
            get;
            set;
        }

        public virtual string CBTLINEDE
        {
            get;
            set;
        }

        public virtual string CBTREMITO
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTBULTOS
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTKILOSN
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTKILOSA
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTMETRCB
        {
            get;
            set;
        }

        public virtual string CBTNOMRTE
        {
            get;
            set;
        }

        public virtual string CBTLOCRTE
        {
            get;
            set;
        }

        public virtual string CBTSUBCLI
        {
            get;
            set;
        }

        public virtual string CBTNOMDES
        {
            get;
            set;
        }

        public virtual string CBTDOMDES
        {
            get;
            set;
        }

        public virtual string CBTLOCDES
        {
            get;
            set;
        }

        public virtual string CBTNRODES
        {
            get;
            set;
        }

        public virtual string CBTDTODES
        {
            get;
            set;
        }

        public virtual string LCLCPOSTA
        {
            get;
            set;
        }

        public virtual string CBTNROHRU
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTVADESE
        {
            get;
            set;
        }

        public virtual string CBTNROCRE
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTIMPCRE
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTFLETET
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTIMPSEG
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTIMPRET
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTIMPENT
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTIMPOTR
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTIMPIVA
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTIIVAAD
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTIMPBON
        {
            get;
            set;
        }

        public virtual string IVACODIGO
        {
            get;
            set;
        }

        public virtual string CLTCUIT
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTPICKIN
        {
            get;
            set;
        }

        public virtual string CBTDESCRI
        {
            get;
            set;
        }

        public virtual string CbtTIPPED
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTPALLET
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTUNIDAD
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> CBTFEPOEN
        {
            get;
            set;
        }

        public virtual string CBTDESCR2
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CBTVDCR
        {
            get;
            set;
        }

        public virtual string CBTSUCORI
        {
            get;
            set;
        }

        public virtual string CbtTivade
        {
            get;
            set;
        }

        public virtual string CbtCuitde
        {
            get;
            set;
        }

        public virtual string CbtFleasi
        {
            get;
            set;
        }

        public virtual string CbtVehasi
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CbtSecuhr
        {
            get;
            set;
        }

        public virtual string CBTDETALL
        {
            get;
            set;
        }

        public virtual string CBTEMAIL
        {
            get;
            set;
        }

        public virtual bool ESCANEADO
        {
            get;
            set;
        }

        public virtual string CbtTelefo
        {
            get;
            set;
        }

        public virtual string CbtAdic1
        {
            get;
            set;
        }

        public virtual string CbtAdic2
        {
            get;
            set;
        }

        public virtual string CbtAdic3
        {
            get;
            set;
        }

        public virtual string CbtAdic4
        {
            get;
            set;
        }

        public virtual string CbtAdic5
        {
            get;
            set;
        }

        public virtual string CbtSenasa
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CbtImpad1
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CbtImpad2
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CbtAbasto
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> CbtPercib
        {
            get;
            set;
        }

        public virtual string CbtTipcar
        {
            get;
            set;
        }

        public virtual string CbtNomdesAlter
        {
            get;
            set;
        }

        public virtual string CbtTivadeAlter
        {
            get;
            set;
        }

        public virtual string CbtCuitdeAlter
        {
            get;
            set;
        }

        public virtual string CbtTelefoAlter
        {
            get;
            set;
        }

        public virtual string CbtCodVerif
        {
            get;
            set;
        }

        public virtual string CbtDatosEntrega
        {
            get;
            set;
        }


        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          RECHRDE toCompare = obj as RECHRDE;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.CBTCENEMI, toCompare.CBTCENEMI))
            return false;
          if (!Object.Equals(this.CBTNROCBT, toCompare.CBTNROCBT))
            return false;
          if (!Object.Equals(this.CBTLETCBT, toCompare.CBTLETCBT))
            return false;
          if (!Object.Equals(this.RHDNROCLI, toCompare.RHDNROCLI))
            return false;
          if (!Object.Equals(this.CBTCODCBT, toCompare.CBTCODCBT))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + CBTCENEMI.GetHashCode();
          hashCode = (hashCode * 7) + CBTNROCBT.GetHashCode();
          hashCode = (hashCode * 7) + CBTLETCBT.GetHashCode();
          hashCode = (hashCode * 7) + RHDNROCLI.GetHashCode();
          hashCode = (hashCode * 7) + CBTCODCBT.GetHashCode();
          return hashCode;
        }
        
        #endregion
    }

}
