//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 02/05/2019 11:34:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;

namespace Calico.PedidosTMS.Model
{
    public partial class CLIENTESACCESOAPI
    {
        public CLIENTESACCESOAPI()
        {
            OnCreated();
        }

        public string CODIGOCLIENTE { get; set; }
        public string USUARIOAPI { get; set; }
        public string PASSWORDAPI { get; set; }
        public string CODIGO_CIA { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }
}
