//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 31/7/2018 12:26:55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;

namespace Calico.PedidosTMS.Model
{
    public partial class RefreshToken
    {
        public RefreshToken()
        {
            OnCreated();
        }

        public int RefreshTokenId { get; set; }
        public DateTime IssuedUtc { get; set; }
        public DateTime ExpiresUtc { get; set; }
        public string Token { get; set; }
        public string CODIGOCLIENTE { get; set; }
        public string USUARIOAPI { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }
}
